version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./data/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-c', '\echo Im alive']
      interval: 4s

  event-service:
    depends_on:
      postgres:
        condition: service_healthy
    image: docker.pkg.github.com/tuuturu/pager-event-service/pager-service:0.0.3
    ports:
      - 3000:3000
    environment:
      DISCOVERY_URL: https://deifyed.eu.auth0.com/.well-known/openid-configuration
      DATABASE_URI: postgres
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  gatekeeper:
    image: docker.pkg.github.com/oslokommune/gatekeeper/gatekeeper:1.0.41
    ports:
    - 4554:4554
    environment:
      BASE_URL: http://localhost:4554
      CLIENT_ID: gxt0YY7fB0MuDmyi99rOWvJXDjTFcSXj
      CLIENT_SECRET: hq0LDh9aEXejt_8qIozotiN4Vrym0pFgBxu9SJLYVC1PKmxmu5PPcc6WQRn_kN2g
      DISCOVERY_URL: https://deifyed.eu.auth0.com/.well-known/openid-configuration
      ORIGIN_WHITELIST: http://localhost:8081
      TOKEN_COOKIES_SECURE: 'false'
      LOG_LEVEL: debug
      LOG_PRETTY_PRINT: 'true'
      UPSTREAMS: |
        events=http://event-service:3000;
